name: invitation_web
description: "A Invitation Web Application"
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.6.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.20.1
  gradient_borders: ^1.0.1
  watch_it: ^1.6.1
  just_audio: ^0.9.42
  url_launcher: ^6.3.1
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  collection: ^1.19.0
  card_loading: ^0.3.2
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#212121"
  image: assets/splash.png
  # image: assets/logo-development.png
  # branding: assets/branding-development.png
  # color_dark: "#121212"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png
  android: false
  ios: false
  web: true
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/avatars/
  
  fonts:
    - family: BrushScriptMT
      fonts:
        - asset: fonts/Brush-Script-MT-Regular.ttf
    - family: Upakarti
      fonts:
        - asset: fonts/Upakarti-Regular.ttf
        - asset: fonts/Upakarti-Italic.ttf
          style: italic
