name: invitation_web
description: "A Invitation Web Application"
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  gradient_borders: ^1.0.0
  get_it: ^7.6.7
  get_it_mixin: ^4.2.2
  responsive_builder: ^0.7.0
  just_audio: ^0.9.38
  url_launcher: ^6.3.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.1.0
  collection: ^1.18.0
  card_loading: ^0.3.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png
  # image: assets/logo-development.png
  # branding: assets/branding-development.png
  # color_dark: "#121212"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png
  android: false
  ios: false
  web: true
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/avatars/
  
  fonts:
    - family: BrushScriptMT
      fonts:
        - asset: fonts/Brush-Script-MT-Regular.ttf
    - family: Upakarti
      fonts:
        - asset: fonts/Upakarti-Regular.ttf
        - asset: fonts/Upakarti-Italic.ttf
          style: italic
